spring:
  application:
    name: backend-demo


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    hostname: 127.0.0.1
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      #defaultZone: http://admin:123456@127.0.0.1:8100/eureka/
      defaultZone: ${EUREKA_SERVICE_URL:http://admin:123456@127.0.0.1:8100}/eureka/